"""add shot_events player_tracks coaching_reports tables

Revision ID: 27d246916587
Revises: 3acab6a83b21
Create Date: 2026-07-04 18:11:56.459656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d246916587'
down_revision: Union[str, None] = '3acab6a83b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_reports',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_reports_job_id'), 'coaching_reports', ['job_id'], unique=False)
    op.create_table('player_tracks',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('speed_ms', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_tracks_job_id'), 'player_tracks', ['job_id'], unique=False)
    op.create_table('shot_events',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('shot_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('speed_km_h', sa.Float(), nullable=False),
    sa.Column('angle_deg', sa.Float(), nullable=False),
    sa.Column('landing_x', sa.Float(), nullable=True),
    sa.Column('landing_y', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_events_job_id'), 'shot_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_events_job_id'), table_name='shot_events')
    op.drop_table('shot_events')
    op.drop_index(op.f('ix_player_tracks_job_id'), table_name='player_tracks')
    op.drop_table('player_tracks')
    op.drop_index(op.f('ix_coaching_reports_job_id'), table_name='coaching_reports')
    op.drop_table('coaching_reports')
    # ### end Alembic commands ###
