"""add artifacts column to analysis jobs

Revision ID: 3acab6a83b21
Revises: a2c95f5cd196
Create Date: 2026-07-04 00:52:04.292701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acab6a83b21'
down_revision: Union[str, None] = 'a2c95f5cd196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('artifacts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'artifacts')
    # ### end Alembic commands ###
